id: I7AD7DD77
legacy_id: P010351
ocr_import_info:
  bdrc_scan_id: W1KG3870
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T01:20:31'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:18:21.871453+00:00'
last_modified: 2022-08-31 23:18:26.419774
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3870
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3870
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བདེ་ཆེན་ཆོས་འཁོར་ཡོངས་འཛིན་ཡེ་ཤེས་གྲུབ་པའི་རྣམ་ཐར།
  author: བདེ་ཆེན་ཆོས་འཁོར་ཞབས་དྲུང ༠༧་ཆོས་ཀྱི་ཉིན་བྱེད།
statistics:
  ocr_word_mean_confidence_index: 0.708913160272669
  ocr_word_median_confidence_index: 0.7900000214576721
quality: null
bases:
  I1KG3951:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3951
      total_pages: 42
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3951.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.708913160272669
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
