id: I7AD7DD77
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T01:20:50+00:00'
last_modified: '2022-06-08T12:57:15.665752+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3870
  title: བདེ་ཆེན་ཆོས་འཁོར་ཡོངས་འཛིན་ཡེ་ཤེས་གྲུབ་པའི་རྣམ་ཐར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    98EA:
      image_group_id: I1KG3951
      title: ''
      total_pages: 42
      order: 1
      base_file: 98EA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
